language: objective-c
osx_image: xcode63
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- pod install
script:
- xctool -scheme RAMReel