language: objective-c
osx_image: xcode63
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- brew update
- pod install
script:
- set -o pipefail
- xcodebuild -scheme "RAMReel" -sdk iphonesimulator